config/routes.rb
Rails.application.routes.draw do
  root :to => 'sections#index'
  resources :sections do
    resources :lessons
  end
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  validates :name, :presence => true
  validates :content, :presence => true
  validates :number, :presence => true
end

app/models/section.rb
class Section < ActiveRecord::Base
 has_many :lessons
 # belongs_to :chapter
 validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @section = Section.find(params[:section_id])
    @lessons = Lesson.order(:number)
  end
  # get rid of index

  def new
      @section = Section.find(params[:section_id])
      @lesson = Lesson.new
  end

  def create
    @section = Section.find(params[:section_id])
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      flash[:notice] = "Lesson successfully added!!"
      redirect_to section_path(@lesson.section_id)
    else
      render :new
    end
  end

  def show
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @previous = Lesson.where("number < ?", @lesson.number).last
    @next = Lesson.where("number > ?", @lesson.number).first
  end

  def edit
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
  end

  def update
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to section_lesson_path(@section, @lesson)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:section_id])
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to section_path(@section)
  end


  private
  def lesson_params
    params.require(:lesson).permit(:name, :content, :number, :section_id)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  def index
    @sections = Section.all
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:notice] = "Section Saved!"
      redirect_to sections_path
    else
      render :new
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to section_path(@section)
    else
      render :edit
    end
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

private
  def section_params
    params.require(:section).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>These errors need fixed:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li class="alert"><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" id="my-navbar">
      <div class="container">
        <div class="navbar-header">

          <button class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>

          <a href="" class="navbar-brand">Don't Learn To Program</a>

        </div><!-- end of navbar header div -->
         <div class="collapse navbar-collapse" id="navbar-collapse">



          <ul class="nav navbar-nav">
          <li><a href="#">FAQ </a></li>
          <li><a href="#">Contact</a></li>
          </ul>
        </div><!-- end of nav that contains ul links -->

      </div><!--end of nav container -->
    </nav><!-- End navbar -->
  <div class="container">
    <p id="notice"><%= flash[:notice] %></p>
    <!-- <p id="alert"><%= flash[:alert] %></p> -->


    <%= yield %>


  </div>


</body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", :object => @lesson %>

<%= form_for [@section, @lesson] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :content %>
  <%= f.text_field :content %>
  <%= f.label :number %>
  <%= f.text_field :number %>
  <%= f.label :section_id %>
  <%= f.collection_select :section_id, Section.all, :id, :title, :selected => @section.id%>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<% content_for :title, "Learn To Program | Edit Lesson" %>


<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/index.html.erb
<!-- # <% content_for :title, "Learn To Program | Lessons" %>
#
# <h1>Index Lessons</h1>
#
# <% if @lessons.any? %>
#   <ul>
#     <% @lessons.each do |lesson| %>
#       <li><%= link_to lesson.name, lesson_path(lesson) %></li>
#     <% end %>
#   </ul>
# <% else %>
#   <p><h3>No Lessons Currently in Index</h3></p>
# <% end %>
#
#
# <%= link_to 'Add a New Lesson', new_section_lesson_path(@section) %> -->

app/views/lessons/new.html.erb
<% content_for :title, "Learn To Program | New Lesson" %>

<h1>New Lesson</h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<% content_for :title, "Learn To Program | Lesson" %>

<h1><%= @lesson.name %></h1>

<p>Content: <%= @lesson.content %></p>

<p>Number: <%= @lesson.number %></p>

<p><%= link_to "Edit", edit_section_lesson_path(@section, @lesson) %></li>
<p><%= link_to "Delete", section_lesson_path(@section, @lesson),
                    :data => {:confirm => "Confirm?",
                    :method => "delete"} %></p>



<% if @next %>
  <%= link_to "Next", section_lesson_path(@section, @next) %>
<% end %>


<% if @previous %>
  <%= link_to "Previous", section_lesson_path(@section, @previous) %>
<% end %>

app/views/sections/_form.html.erb
<%= render "layouts/errors", :object => @section %>

<%= form_for @section do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/sections/edit.html.erb
<% content_for :title, "Learn To Program | Edit Section" %>


<h1>Edit Section</h1>

<%= render "form" %>

app/views/sections/index.html.erb
<% content_for :title, "Learn To Program | Sections" %>

<h1>Index Sections</h1>

<% if @sections.any? %>
   <ul>
     <% @sections.each do |section| %>
       <li><%= link_to section.title, section_path(section) %></li>
     <% end %>
   </ul>
<% else %>
   <p><h3>No Sections Currently in Index</h3></p>
 <% end %>


<%= link_to 'Add a New Section', new_section_path %>

app/views/sections/new.html.erb
<% content_for :title, "Learn To Program | New Section" %>

<h1>New Section</h1>

<%= render "form" %>

app/views/sections/show.html.erb
<h3><%= @section.title %></h3>

<%if @section.lessons.any? %>
  <h3>Lessons in this section:</h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th width='200px'>Lesson Name:</th>
        <th>Content:</th>
      </tr>
    </thead>
    <tbody>
      <% @section.lessons.each do |lesson| %>
        <tr>

          <td><%= link_to lesson.name, section_lesson_path(@section, lesson)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>There are no lessons in this category yet.</h3>
<% end %>

<p><%= link_to "Edit Section", edit_section_path(@section) %></li>
<p><%= link_to "Delete", section_path(@section),
                    :data => {:confirm => "Confirm?",
                    :method => "delete"} %></p>

<br>


<%= link_to 'Add a New Lesson', new_section_lesson_path(@section) %>